nome: Gerar Dados

em:
 horário:
    - cron: "0*/12****"
 fluxo de trabalho_despacho:

empregos:
 construir:
 nome: Empregos para atualizar dados
 corre: ubuntu-último
 passos:
      - usos: ações/checkout@v2

      - usos: Platane/snk@master
 com:
 github_user_name: luizandradedm
 svg_out_path: dist/github-contribution-grid-snake.svg
 caminho Gif_out_: dist/github-contribution-grid-snake.gif

      - usos: crazy-max/ghaction-github-pages@v2.1.3
 com:
 target_branch: saída
 construir_dir: dist
 env:
 GITHUB_TOKEN: ${{ segredos.GITHUB_TOKEN }}
